### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by Alhajideen** [ndorrh/portfolio#8]
# Code-review

Nice design. I like the way your images are adaptive and fits on all screen sizes.
However there are few things i think you can do to make your design more beautiful;
-I think you can remove the line height on your buttons, this would stop the button contents from moving during animations
-I also think may be better to animate only the paragraph in your about me section. This will give viewers a knowledge of what should be there before the paragraph slide in.
-I also think you should remove the height on your footer, this will help get rid of the empty space there.

DO have a beautiful weekend :)

**Comment by OscarFMdev** [comment]
### Congratulations so far!

I really like how it's looking, I especially like the buttons transition and also I agree with Deen's review to make your design even better. Please check the requirements described by Deen and if you have trouble with something don't hesitate to send us a message!

Cheers and happy coding! :computer: :1st_place_medal: :clap: :clap:
